#!/usr/bin/env python3
"""Copy the argument hashes out of mcp-server's catalogue into src/catalog.rs.

The catalogue belongs to mcp-server: it owns the argument schemas, so it owns their hashes. This
bot only has to agree, and a hash it made up would agree with nothing but itself.

Every tool a bot could answer is copied, not only the ones the catalogue already offers to this
kind. Which kinds may run a tool is the catalogue's to say and the server's to enforce at the
handshake; the bot reports what it implements and nothing else.

    hack/sync-catalog.py                        # ../mcp-server/catalog/catalog.json
    hack/sync-catalog.py path/to/catalog.json
    hack/sync-catalog.py --from v0.61.3         # the catalogue mcp-server released under that tag

The generated file names where it came from as CATALOG_SOURCE. With `--from` that is the release
tag, which is what CI regenerates from and diffs against, so a catalogue edited by hand or synced
from a working tree that never shipped shows up as a diff rather than as a hash the server does not
hold. A local path is recorded as it was given, and CI cannot check it.
"""

import hashlib
import json
import pathlib
import sys
import urllib.request

RELEASED = "https://raw.githubusercontent.com/mc-agents/mcp-server/%s/catalog/catalog.json"

REPO = pathlib.Path(__file__).resolve().parent.parent
DEFAULT = REPO.parent / "mcp-server/catalog/catalog.json"
TARGET = REPO / "src/catalog.rs"

# A composed tool is half a bot call and half something mcp-server does with its own buffers, so
# the bot implements it like any other.
ROUTES_A_BOT_ANSWERS = {"rpc", "compose"}


def canonical(value):
    if isinstance(value, dict):
        return {key: canonical(value[key]) for key in sorted(value)}
    if isinstance(value, list):
        return [canonical(item) for item in value]
    return value


def digest(value):
    encoded = json.dumps(canonical(value), separators=(",", ":"), ensure_ascii=False).encode()
    return "sha256:" + hashlib.sha256(encoded).hexdigest()


arguments = sys.argv[1:]
if arguments[:1] == ["--from"]:
    if len(arguments) != 2:
        raise SystemExit(__doc__)
    label = arguments[1]
    with urllib.request.urlopen(RELEASED % label) as response:
        catalog = json.load(response)
else:
    label = arguments[0] if arguments else "../mcp-server/catalog/catalog.json"
    catalog = json.loads((pathlib.Path(arguments[0]) if arguments else DEFAULT).read_text())

tools = sorted(
    # A tool with no wire schema sends a bot nothing of its own: a wait polls another tool, and
    # that one is what crosses the wire.
    (tool for tool in catalog["tools"] if tool["route"] in ROUTES_A_BOT_ANSWERS and tool.get("wireSchema")),
    key=lambda tool: tool["name"],
)

for tool in tools:
    if tool.get("wireSchemaHash") != digest(tool["wireSchema"]):
        raise SystemExit("%s: the catalogue's own hash does not describe its schema" % tool["name"])

entries = "\n".join('    ("%s", "%s"),' % (tool["name"], tool["wireSchemaHash"]) for tool in tools)

TARGET.write_text('''//! Generated by hack/sync-catalog.py from mcp-server's catalog.json. Do not edit by hand.

pub const CATALOG_VERSION: &str = "%s";
/// The mcp-server release the catalogue was read from. CI regenerates from it and expects no diff.
pub const CATALOG_SOURCE: &str = "%s";
pub const PROTOCOL: u32 = %d;

/// The argument hash the catalogue gives each tool a bot could answer, sorted by name.
#[rustfmt::skip]
pub const ARGS_HASHES: &[(&str, &str)] = &[
%s
];

pub fn args_hash(tool: &str) -> Option<&'static str> {
    ARGS_HASHES
        .binary_search_by(|(name, _)| name.cmp(&tool))
        .ok()
        .map(|index| ARGS_HASHES[index].1)
}
''' % (catalog["catalogVersion"], label, catalog["protocol"], entries))

print("%s: %d tools from catalogue %s (%s)" % (TARGET.relative_to(REPO), len(tools), catalog["catalogVersion"], label))
